
const motives = [
  "Bugün harika bir gün olabilir, yeter ki sen iste.",
  "Şans hazır olanı sever.",
  "Küçük bir adım, büyük değişimlerin başlangıcıdır.",
  "Pes etme, belki de zafer bir sonraki denemededir.",
  "Gülümse, çünkü enerjin çevreni etkiler.",
  "Unutma: En karanlık an, şafağa en yakın olandır.",
  "Hayat, cesur adımlarla değişir.",
  "Bugün senin günün olabilir!",
  "Güzellikler seni bekliyor.",
  "İyi şeyler zaman alır.",
  "Her şey yoluna girecek.",
  "İçindeki güce güven.",
  "Sen yeter ki iste.",
  "Her yeni gün bir şanstır.",
  "Yarınlar umutla gelir.",
  "Kalbinin sesini dinle.",
  "Kendine inan.",
  "Başarı sabır ister.",
  "Vazgeçme!",
  "Güzel günler yakında.",
  "Yolun açık olsun.",
  "Kendin ol.",
  "Yapabilirsin.",
  "Bugün bir mucize olabilir.",
  "Umut hep vardır.",
  "Karanlıkta bile ışık var.",
  "Bir tebessüm yeter.",
  "Sen değerlisin.",
  "Hedefine odaklan.",
  "Her şey mümkün.",
  "Pozitif düşün.",
  "İnan, başar.",
  "Kendine bir iyilik yap.",
  "Bugün daha iyi ol.",
  "Şükretmeyi unutma.",
  "Her adım kıymetlidir.",
  "Korkma, dene.",
  "Cesaret bulaşıcıdır.",
  "Sakin ol, geçecek.",
  "Hayallerine sarıl.",
  "Zorluklar geçici.",
  "Sabret, çaba göster.",
  "Kıymet bil.",
  "Bugünü yaşa.",
  "Anda kal.",
  "Gülümse.",
  "Yorgunsan dinlen.",
  "Umut et.",
  "Affet.",
  "Sev.",
  "Hisset.",
  "Seninle gurur duyuyorum.",
  "Gücün farkında mısın?",
  "Bugün çok güzelsin.",
  "Harikasın!",
  "Sen özelsin.",
  "Kendine zaman ayır.",
  "İyi ki varsın.",
  "Yalnız değilsin.",
  "Dostların seni seviyor.",
  "İyi bir insansın.",
  "Bunu hak ediyorsun.",
  "Çok çalıştın.",
  "Mola ver.",
  "Sen bir ışıksın.",
  "Neşe saç.",
  "Kendi kahramanın ol.",
  "Kendini sev.",
  "İzin ver iyilik gelsin.",
  "İç huzurun önemli.",
  "Bugün fark yarat.",
  "Günün ilham kaynağı sensin.",
  "Senin için buradayım.",
  "Kendinle gurur duy.",
  "Kendine nazik ol.",
  "Düşüncelerin değerli.",
  "Gönlünü ferah tut.",
  "İçindeki çocuk gülümsesin.",
  "Yarın yeni bir fırsat.",
  "Uyan, derin nefes al.",
  "Senin hikayen yeni başlıyor.",
  "Işığın hiç sönmesin.",
  "Umut hep sende kalsın.",
  "Bugün en güzel günün olsun.",
  "Her şeyin bir zamanı var.",
  "Zamanla her şey olur.",
  "Senin zamanın şimdi.",
  "Hayat güzel, sen de.",
  "Haydi başla!",
  "Harekete geç.",
  "Bekleme.",
  "Denemekten korkma.",
  "Kalbini aç.",
  "İçinden geldiği gibi yaşa.",
  "Kendine dürüst ol.",
  "Sen değiş, dünya değişir.",
  "Güzel haberler al.",
  "Mutluluğu seç.",
  "Denge kur.",
  "İyiliğe alan aç.",
  "Düşün, hisset, yaşa.",
  "Senin gücün yeter.",
  "Gülüşün her şeye değer."
];

let motiveCount = 0;
function newMotive() {
  motiveCount++;
  const el = document.getElementById("motive");
  if (motiveCount > 2) {
    el.textContent = ""Artık başka cümle yok... Cafede dertleşiriz ☕"";
    return;
  }
  el.textContent = motives[Math.floor(Math.random() * motives.length)];
}
